### ISSUE TITLE
是否有后期计划呢？

### ISSUE THREAD

**Issue by ununian** [booiris/pikpakcli_rust#10]
还在快速开发中吗？ 会对齐go版本吗？ 
我前几天也想开发个类似的，没想到就这几天就有了，如果有需要的话我可以帮忙一起开发，我怕弄重复了。
另外能不能把pikpak相关的逻辑封装成库呢，那样方便二次开发点。

**Comment by booiris** [comment]
因为只是自用的目的，所以开发完 download 接口之后迭代应该就没那么快了。当然欢迎 pr，不过你最好还是 fork 一个写吧，因为不保证以后会对齐 go 版本 🌝 。封装的话现在代码也不多，copy 一下就行了吧。
